version: '2'
services:
  web:
    image: examples/spring-boot-rest-example-mysql
    ports:
    - "8090:8090"
    - "8091:8091"
    depends_on:
    - mysql
  mysql:
    image: mysql:5.6
    volumes:
    - /opt/testdata:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=adminadmin
    - MYSQL_DATABASE=bootexample
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
